# Generated by Django 2.2 on 2019-05-09 01:12

from django.db import migrations

def insert_source_types(apps,schema_editor):
    source_type = apps.get_model('api', 'SourceType')
    upload = source_type(name='Upload')
    upload.save()
    rss = source_type(name='RSS')
    rss.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
	   migrations.RunPython(insert_source_types)
    ]


