# Generated by Django 2.2 on 2019-04-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dummy',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_match',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='sources',
            field=models.ManyToManyField(blank=True, to='api.Source'),
        ),
    ]
