# Generated by Django 2.2 on 2019-04-30 00:46

from django.db import migrations

def insert_source_types(apps,schema_editor):
    source_type = apps.get_model('api', 'SourceType')
    upload = source_type(name='Upload')
    upload.save()
    rss = source_type(name='RSS')
    rss.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190430_0033'),
    ]

    operations = [
    ]
