# Generated by Django 2.2 on 2019-05-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190509_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintstream',
            name='is_integrator',
            field=models.BooleanField(default=False, verbose_name='integrator status'),
        ),
    ]
