# Generated by Django 2.2 on 2019-04-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_auto_20190430_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Source')),
                ('url', models.URLField(max_length=1000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.source',),
        ),
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadSource',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='uploadsource',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='uploadsource',
            name='sourcetype_ptr',
        ),
        migrations.AddField(
            model_name='source',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.source_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='uploadsource',
            name='source_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Source'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rss',
        ),
    ]
