# Generated by Django 2.2 on 2019-05-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190513_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='base64_encoded_model',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
