# Generated by Django 2.2.5 on 2019-09-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190902_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_key', models.CharField(max_length=100)),
                ('aws_secret', models.CharField(max_length=250)),
                ('aws_region', models.CharField(max_length=15)),
            ],
        ),
    ]
