# Generated by Django 2.2.5 on 2019-09-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Article')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.article',),
        ),
        migrations.CreateModel(
            name='WordDocxArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Article')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.article',),
        ),
        migrations.RemoveField(
            model_name='article',
            name='match_article',
        ),
        migrations.AddField(
            model_name='article',
            name='match_articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='_article_match_articles_+', to='api.Article'),
        ),
    ]
