# Generated by Django 2.2.5 on 2019-09-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190906_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Source')),
                ('script_path', models.TextField(max_length=500)),
                ('working_dir', models.TextField(max_length=500)),
                ('virtual_env_path', models.TextField(max_length=500)),
                ('python_binary_fullpath', models.TextField(max_length=500)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.BooleanField(blank=True, null=True)),
                ('arguments', models.TextField(max_length=1000)),
                ('task', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.source',),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='sources',
            field=models.ManyToManyField(to='api.Source'),
        ),
    ]
