# Generated by Django 2.2.5 on 2019-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190908_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfarticle',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
