# Generated by Django 2.2.5 on 2019-09-10 00:37

from django.db import migrations, models

def insert_source_type(apps,schema_editor):
    source_type = apps.get_model('api', 'SourceType')
    rss = source_type(name='Job')
    rss.save()

def set_api_endpoints():

    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190910_0000'),
    ]

    operations = [
        migrations.RunPython(insert_source_type),

    ]
