# Generated by Django 2.2.5 on 2019-09-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sourcetype_api_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.TextField(max_length=100, unique=True)),
            ],
        ),
    ]
