# Generated by Django 2.2.5 on 2019-09-10 00:57

from django.db import migrations
from ..urls import HTMLARTICLES, PDFARTICLES, TXTARTICLES, DOCXARTICLES
from backend.urls import API

def insert_article_types(apps,schema_editor):
    article_type = apps.get_model('api', 'ArticleTypes')
    article = article_type(name='PDF',api_endpoint=API + PDFARTICLES)
    article.save()
    article = article_type(name='HTML',api_endpoint=API + HTMLARTICLES)
    article.save()
    article = article_type(name='TXT',api_endpoint=API + TXTARTICLES)
    article.save()
    article = article_type(name='DOCX',api_endpoint=API + DOCXARTICLES)
    article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_articletypes'),
    ]

    operations = [
        migrations.RunPython(insert_article_types)
    ]
