# Generated by Django 2.2.5 on 2019-09-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190910_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTypes',
            new_name='ArticleType',
        ),
        migrations.RemoveField(
            model_name='sourcetype',
            name='active',
        ),
    ]
