# Generated by Django 2.2.5 on 2019-09-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190910_0115'),
    ]

    operations = [
    ]
