# Generated by Django 2.2.5 on 2019-09-11 00:46

from django.db import migrations, models
from ..urls import RSSSOURCE, UPLOADSOURCE, JOBSOURCE

import uuid

def sourcetype_api_endpoints(apps,schema_editor):
    sourcetype = apps.get_model('api', 'SourceType')
    sourcetype.objects.filter(name="RSS").update(api_endpoint=RSSSOURCE)
    sourcetype.objects.filter(name="Upload").update(api_endpoint=UPLOADSOURCE)
    sourcetype.objects.filter(name="Job").update(api_endpoint=JOBSOURCE)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190910_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='api_endpoint',
            field=models.TextField(default=str(uuid.uuid4()), max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(sourcetype_api_endpoints),
        migrations.AlterField(
            model_name='sourcetype',
            name='api_endpoint',
            field=models.TextField( max_length=50,unique=True),
            preserve_default=False,
        ),

    ]
