# Generated by Django 2.2.5 on 2019-10-06 00:26

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190911_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rssarticle',
            name='link',
            field=models.URLField(default='http://test.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssarticle',
            name='quid',
            field=models.CharField(default=uuid.uuid4(), max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
