# Generated by Django 2.2.5 on 2019-10-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191007_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.AddField(
            model_name='htmlarticle',
            name='file',
            field=models.FileField(default='', upload_to='article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfarticle',
            name='file',
            field=models.FileField(default='', upload_to='article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txtarticle',
            name='file',
            field=models.FileField(default='', upload_to='article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worddocxarticle',
            name='file',
            field=models.FileField(default='', upload_to='article'),
            preserve_default=False,
        ),
    ]
