# Generated by Django 2.2.6 on 2019-10-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191007_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='match_articles',
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Article'),
        ),
    ]
