# Generated by Django 2.2.6 on 2019-11-01 18:06
import uuid

from django.db import migrations, models

def create_uuid(apps, schema_editor):
    sources = apps.get_model('api', 'Source')
    for source in sources.objects.all():
        source_names = [x.name for x in sources.objects.exclude(source_id=source.id).all()]
        if source.name in source_names:
            source.name = source.name + str(uuid.uuid4())
        source.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191018_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
