# Generated by Django 2.2.6 on 2019-11-02 01:37
import pdb
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.models import User
def add_org(apps, schema_editor):
    org_model = apps.get_model('api', 'Organization')
    article_model = apps.get_model('api','Article')
    cat_model = apps.get_model('api','Categories')
    mlmodel_model = apps.get_model('api','MLModel')
    settings_model = apps.get_model('api','Settings')
    source_model = apps.get_model('api','Source')
    usr_model = apps.get_model('api','UserIntstream')

    num_orgs = org_model.objects.count()
    num_users = usr_model.objects.count()
    # if existing users and upgrading
    # add an org and associate it.
    if num_orgs == 0 and num_users !=0:
        org = org_model.objects.create(name="default")
        for user in usr_model.objects.all():
            user.organization = org
            user.save()
        for article in article_model.objects.all():
            article.organization = org
            article.save()
        for cat in cat_model.objects.all():
            cat.organization = org
            cat.save()
        for model in mlmodel_model.objects.all():
            model.organization = org
            model.save()
        for setting in settings_model.objects.all():
            setting.organization = org
            setting.save()
        for source in source_model.objects.all():
            source.organization = org
            source.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191101_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userintstream',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        # insert update action here
        migrations.RunPython(add_org),
        migrations.AlterField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='organization',
            field=models.ForeignKey( null=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='organization',
            field=models.ForeignKey( null=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userintstream',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),

    ]
