# Generated by Django 2.2.6 on 2019-11-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191102_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='source',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='userintstream',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
    ]
