# Generated by Django 2.2.6 on 2019-11-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20191115_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='api.MLModel'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='base64_encoded_model',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
