# Generated by Django 2.2.6 on 2019-12-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20191203_2230'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.UniqueConstraint(fields=('article', 'mlmodel', 'organization'), name='unique_classification'),
        ),
    ]
