# Generated by Django 2.2.6 on 2019-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191205_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.AddField(
            model_name='article',
            name='match',
            field=models.ManyToManyField(blank=True, null=True, related_name='_article_match_+', to='api.Article'),
        ),
    ]
