# Generated by Django 2.2.6 on 2019-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20191206_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='similarity_threshold',
            field=models.IntegerField(default=0.7),
            preserve_default=False,
        ),
    ]
