# Generated by Django 2.2.6 on 2019-12-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_settings_similarity_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
