# Generated by Django 2.2.6 on 2019-12-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20191211_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='match',
        ),
    ]
