# Generated by Django 3.0.1 on 2020-01-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_article_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_key', models.CharField(max_length=100)),
                ('aws_secret', models.CharField(max_length=250)),
                ('aws_region', models.CharField(max_length=15)),
                ('aws_s3_log_base', models.CharField(max_length=500)),
                ('aws_s3_upload_base', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userintstream',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_name'),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='setting',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
    ]
