# Generated by Django 3.0.2 on 2020-01-21 02:40

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200118_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aws_key',
            field=fernet_fields.fields.EncryptedTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='aws_secret',
            field=fernet_fields.fields.EncryptedTextField(max_length=250),
        ),
    ]
