# Generated by Django 3.0.2 on 2020-01-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200120_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rssarticle',
            name='guid',
            field=models.CharField(max_length=200),
        ),
    ]
