# Generated by Django 3.0.2 on 2020-01-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200120_2217'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mlmodel',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_model_name'),
        ),
    ]
