# Generated by Django 3.0.2 on 2020-02-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200207_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelversion',
            name='selected',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='version_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ModelVersion'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
