# Generated by Django 2.2 on 2020-02-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_setting_ec2_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='virtual_env_loc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
