# Generated by Django 2.2 on 2020-02-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_modelversion_virtual_env_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.BooleanField(verbose_name='target classification')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='modelversion',
            name='unique_model_version',
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='mlmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MLModel'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('article', 'mlmodel', 'organization'), name='unique_model_classification'),
        ),
    ]
