# Generated by Django 2.2 on 2020-02-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20200219_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='script_directory',
            field=models.CharField(default='uuid-original-default', max_length=500),
        ),
    ]
