# Generated by Django 2.2 on 2020-02-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200221_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodelactiveversion',
            name='model',
        ),
        migrations.AddConstraint(
            model_name='mlmodelactiveversion',
            constraint=models.UniqueConstraint(fields=('version', 'organization'), name='unique_version_org'),
        ),
    ]
