# Generated by Django 2.2 on 2020-02-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200221_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelActiveVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MLModel')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ModelVersion')),
            ],
        ),
        migrations.DeleteModel(
            name='MLModelActiveVersion',
        ),
        migrations.AddConstraint(
            model_name='modelactiveversion',
            constraint=models.UniqueConstraint(fields=('model', 'organization'), name='unique_version_org'),
        ),
    ]
