# Generated by Django 2.2 on 2020-02-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200223_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelversion',
            name='start_classify',
        ),
        migrations.AddField(
            model_name='modelversion',
            name='celery_log',
            field=models.FileField(blank=True, null=True, upload_to='celery_logs'),
        ),
        migrations.CreateModel(
            name='ClassifyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_classify', models.DateTimeField(blank=True, null=True)),
                ('end_classify', models.DateTimeField(blank=True, null=True)),
                ('task', models.CharField(max_length=500)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ModelVersion')),
            ],
        ),
    ]
