# Generated by Django 2.2 on 2020-03-06 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200226_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
