# Generated by Django 2.2 on 2020-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200305_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rssarticle',
            name='guid',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='rssarticle',
            name='link',
            field=models.URLField(max_length=2000),
        ),
    ]
