# Generated by Django 2.2 on 2020-04-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200314_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='extra_kwargs',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
