# Generated by Django 2.2 on 2020-04-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_modelversion_extra_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='extra_kwargs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
