# Generated by Django 2.2 on 2020-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200331_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='extra_kwargs',
            field=models.CharField(default='{}', max_length=1000),
            preserve_default=False,
        ),
    ]
