# Generated by Django 2.2 on 2020-07-03 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20200501_2010'),
    ]

    operations = [
       migrations.CreateModel(
            name='TrainingScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingScriptVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='train_scripts')),
                ('version', models.TextField(default='0.0.1', max_length=10)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
                ('script', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScript')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingscript',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_script'),
        ),
        migrations.AddConstraint(
            model_name='trainingscriptversion',
            constraint=models.UniqueConstraint(fields=('script', 'version', 'organization'), name='unique_script_version'),
        ),

   ]
