# Generated by Django 2.2 on 2020-07-03 01:36
import os
import tempfile

from django.db import migrations
from django.core.files import File
from django.conf import settings


def insert(apps,schema_editor):
    #needed models
    script_model = apps.get_model('api', 'TrainingScript')
    script_version_model = apps.get_model('api', 'TrainingScriptVersion')
    org_model = apps.get_model("api", "Organization")

    # create system org
    system_org = org_model(name=settings.SYSTEM_ORG)
    system_org.save()

    # create default script name
    default_script = script_model(name="default", organization=system_org)
    default_script.save()

    #create default training script version
    with open(os.path.join(settings.BASE_DIR,"aws_training_files/default.zip"), "rb") as f:
        tf = tempfile.NamedTemporaryFile(dir=os.path.join(settings.BASE_DIR,"media"))
        tf.write(f.read())
        version = script_version_model(script=default_script,
                                       version="1.1.1",
                                       zip=File(tf),
                                       organization=system_org)
        version.save()




class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20200702_2135'),
    ]

    operations = [

        migrations.RunPython(insert),
    ]
