# Generated by Django 2.2 on 2020-07-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20200702_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='training_script_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScriptVersion'),
            preserve_default=False,
        ),
    ]
