# Generated by Django 2.2 on 2020-07-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_mlmodel_training_script_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='training_script_version',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='training_script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScript'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelversion',
            name='training_script_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScriptVersion'),
            preserve_default=False,
        ),
   ]
