# Generated by Django 2.2 on 2020-07-08 01:33

from django.db import migrations
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200706_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingscriptversion',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False),
        ),
    ]
