# Generated by Django 2.2 on 2020-07-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20200707_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='training_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScript'),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='training_script_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScriptVersion'),
        ),
    ]
