# Generated by Django 2.2 on 2020-07-25 19:58

from django.db import migrations

import os
from django.db import migrations
from django.conf import settings


def generate_superuser(apps, schema_editor):

    DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME','intstreamadmin')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL','intstreamadmin@intstream.com')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD','changeme@')

    from api.models import Organization
    from api.models import UserIntStream

    # system org
    system_org = Organization.objects.only("id","name").get(name=settings.SYSTEM_ORG)

    superuser = UserIntStream.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD,
        organization=system_org)

    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0065_auto_20200710_1612'),
    ]
    operations = [
        migrations.RunPython(generate_superuser),
    ]
