# Generated by Django 2.2 on 2020-08-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200801_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userintstream',
            name='is_email_confirmed',
        ),
    ]
