# Generated by Django 2.2 on 2020-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_userintstream_is_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintstream',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
