# Generated by Django 2.2 on 2020-09-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200914_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='extract_indicators',
            field=models.BooleanField(default=False),
        ),
    ]
