# Generated by Django 2.2 on 2020-09-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_indicator_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='freemium',
            field=models.BooleanField(default=True),
        ),
    ]
