# Generated by Django 2.2 on 2020-09-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_organization_freemium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='freemium',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_freemium',
            field=models.BooleanField(default=True, verbose_name='freemium account'),
        ),
    ]
