# Generated by Django 2.2 on 2020-09-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20200917_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_freemium',
        ),
    ]
