# Generated by Django 2.2 on 2020-09-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_organization_freemium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='freemium',
            field=models.TextField(),
        ),
    ]
