# Generated by Django 2.2 on 2020-09-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20200917_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='freemium',
            field=models.BooleanField(default=False),
        ),
    ]
