# Generated by Django 2.2 on 2020-09-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20200917_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='freemium',
        ),
    ]
