# Generated by Django 2.2 on 2020-09-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_organization_freemium'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsource',
            name='test',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
