# Generated by Django 2.2 on 2020-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_jobsource_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
