# Generated by Django 2.2 on 2020-09-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_organization_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='free',
            new_name='freemium',
        ),
        migrations.RemoveField(
            model_name='jobsource',
            name='test',
        ),
    ]
