# Generated by Django 2.2 on 2020-09-20 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20200917_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorNetLoc',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Indicator')),
                ('subdomain', models.TextField(max_length=63, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='[^a-zA-Z0-9\\-]')])),
                ('domain', models.TextField(max_length=63, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='[^a-zA-Z0-9\\-]')])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.indicator',),
        ),
        migrations.CreateModel(
            name='TLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='indicatorcustomtype',
            name='name',
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name='IndicatorDomain',
        ),
        migrations.AddField(
            model_name='indicatornetloc',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TLD'),
        ),
    ]
