# Generated by Django 2.2 on 2020-09-20 20:15
# Generated by Django 2.2 on 2020-09-20 20:01

from django.db import migrations
from django.conf import settings
import requests

def insert(apps, schema_editor):
    proxies = {
        "https": settings.PROXY,
        "http": settings.PROXY
    }
    res = requests.get("https://data.iana.org/TLD/tlds-alpha-by-domain.txt",
                       proxies=proxies,
                       timeout=120)
    tld_model = apps.get_model('api', 'TLD')
    for i in res.text.split("\n"):
        tld = tld_model(value=i)
        tld.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20200920_1615'),
    ]

    operations = [
        migrations.RunPython(insert),
    ]
