# Generated by Django 2.2 on 2020-09-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20200920_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatornetloc',
            name='tld',
        ),
        migrations.DeleteModel(
            name='TLD',
        ),
        migrations.AddField(
            model_name='indicatornetloc',
            name='suffix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Suffix'),
            preserve_default=False,
        ),
    ]
