# Generated by Django 2.2 on 2020-09-22 01:01

from django.db import migrations
from django.conf import settings
import requests
import re


PUBLIC_SUFFIX_RE = re.compile(r'^(?P<suffix>[.*!]*\w[\S]*)', re.UNICODE | re.MULTILINE)

def insert(apps, schema_editor):
    proxies = {
        "https": settings.PROXY,
        "http": settings.PROXY
    }
    suffix_model = apps.get_model('api', 'Suffix')
    resp = requests.get(settings.SUFFIX_LIST_URL, proxies=proxies, timeout=60)
    resp.raise_for_status()
    text, _, _ = resp.text.partition('// ===BEGIN PRIVATE DOMAINS===')
    tlds = [m.group('suffix') for m in PUBLIC_SUFFIX_RE.finditer(text)]
    for x in tlds:
        suffix = suffix_model(value=x)
        suffix.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20200921_2126'),
    ]

    operations = [
        migrations.RunPython(insert),
    ]
