# Generated by Django 2.2 on 2020-09-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20200921_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suffix',
            name='value',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
