# Generated by Django 2.2 on 2020-10-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20200928_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
    ]
