# Generated by Django 2.2 on 2020-10-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20200930_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, to='api.Article'),
        ),
    ]
