# Generated by Django 2.2 on 2020-10-07 00:42

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20201006_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsource',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsource',
            name='user',
            field=models.TextField(default='temp', max_length=250),
            preserve_default=False,
        ),
    ]
