# Generated by Django 2.2 on 2020-10-11 20:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20201006_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobversion',
            old_name='script',
            new_name='zip',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='train_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='articles',
            field=models.ManyToManyField(blank=True, to='api.Article'),
        ),
        migrations.AlterField(
            model_name='indicatormd5',
            name='value',
            field=models.TextField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='must be valid md5 hash', regex='^[0-9a-fA-F]{32}$')]),
        ),
        migrations.AlterField(
            model_name='indicatorsha1',
            name='value',
            field=models.TextField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='must be valid sha1', regex='^[0-9a-fA-F]{40}$')]),
        ),
        migrations.AlterField(
            model_name='indicatorsha256',
            name='value',
            field=models.TextField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='must be valid sha256', regex='^[0-9a-fA-F]{64}$')]),
        ),
    ]
