# Generated by Django 2.2 on 2020-10-12 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20201011_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='organization',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
    ]
