# Generated by Django 2.2 on 2020-10-18 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20201012_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatornetloc',
            name='subdomain',
            field=models.TextField(blank=True, max_length=63, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='[^a-zA-Z0-9\\-]')]),
        ),
    ]
