# Generated by Django 2.2 on 2020-10-25 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20201017_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorEmail',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Indicator')),
                ('value', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.indicator',),
        ),
        migrations.AlterField(
            model_name='indicatoripv4',
            name='ttl',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='indicatoripv6',
            name='ttl',
            field=models.IntegerField(default=14),
        ),
    ]
