# Generated by Django 2.2 on 2020-11-02 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_rawarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('python_version', models.TextField(max_length=3)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.BooleanField(blank=True, null=True)),
                ('arguments', models.TextField(default='', max_length=1000)),
                ('user', models.TextField(max_length=250)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('timeout', models.IntegerField(default=600)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Source')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stderr', models.TextField()),
                ('stdout', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IndicatorJob')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorJobVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='job_scripts')),
                ('version', semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.IndicatorJob')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorNumericField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Indicator')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Indicator')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('python_version', models.TextField(max_length=3)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.BooleanField(blank=True, null=True)),
                ('arguments', models.TextField(default='', max_length=1000)),
                ('cron_day_of_week', models.TextField(max_length=20)),
                ('cron_day_of_month', models.TextField(max_length=10)),
                ('crontab_month_of_year', models.TextField(max_length=20)),
                ('cron_hour', models.TextField(max_length=10)),
                ('cron_minute', models.TextField(max_length=10)),
                ('user', models.TextField(max_length=250)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('timeout', models.IntegerField(default=600)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stderr', models.TextField()),
                ('stdout', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.AlterField(
            model_name='jobversion',
            name='job',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
        migrations.DeleteModel(
            name='JobSource',
        ),
        migrations.AddConstraint(
            model_name='indicatorjobversion',
            constraint=models.UniqueConstraint(fields=('job', 'version', 'organization'), name='indicator_unique_job_version'),
        ),
    ]
