# Generated by Django 2.2 on 2020-11-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20201105_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorTypes',
            new_name='IndicatorType',
        ),
        migrations.DeleteModel(
            name='IndicatorUrl',
        ),
    ]
