# Generated by Django 2.2 on 2020-11-05 18:43

from django.db import migrations


def insert_source_types(apps, schema_editor):
    itype = apps.get_model('api', 'IndicatorType')
    inds = ["IPV4", "IPV6", "Sha256", "Sha1", "MD5", "NetLoc", "Email"]
    for i in inds:
        value = itype(name=i)
        value.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20201105_1413'),
    ]

    operations = [
        migrations.RunPython(insert_source_types)
    ]
