# Generated by Django 2.2 on 2020-11-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20201105_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorjob',
            name='password',
        ),
        migrations.AlterField(
            model_name='indicatorjob',
            name='arguments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
