# Generated by Django 2.2 on 2020-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20201112_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorjob',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
