# Generated by Django 2.2 on 2020-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20201113_1359'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indicatorjob',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_indicatorjob'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_job'),
        ),
    ]
