# Generated by Django 2.2 on 2020-11-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20201113_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='crontab_month_of_year',
            new_name='cron_month_of_year',
        ),
    ]
