# Generated by Django 2.2 on 2020-12-14 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20201113_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatornumericfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicatortextfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='IndicatorTextFieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorNumericFieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
    ]
