# Generated by Django 2.2 on 2020-12-08 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20201113_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='upload_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
