# Generated by Django 2.2 on 2020-12-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20201213_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorNumericFieldName',
        ),
        migrations.DeleteModel(
            name='IndicatorTextFieldName',
        ),
    ]
