# Generated by Django 2.2 on 2020-12-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_indicator_ind_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indicatornumericfield',
            constraint=models.UniqueConstraint(fields=('indicator', 'name', 'organization'), name='unique_numeric_col'),
        ),
        migrations.AddConstraint(
            model_name='indicatortextfield',
            constraint=models.UniqueConstraint(fields=('indicator', 'name', 'organization'), name='unique_text_col'),
        ),
    ]
