# Generated by Django 2.2 on 2021-01-07 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('django_celery_results', '0007_remove_taskresult_hidden'),
        ('api', '0113_auto_20201220_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.TaskResult')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
        migrations.CreateModel(
            name='OrgPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
