# Generated by Django 2.2 on 2021-01-21 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20210112_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='upload_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='indicatornumericfield',
            name='update_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='indicatortextfield',
            name='update_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
