# Generated by Django 2.2 on 2021-01-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20210120_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='arguments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_day_of_month',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_day_of_week',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_hour',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_minute',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_month_of_year',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
