# Generated by Django 2.2 on 2021-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20210123_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cron_day_of_month',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_day_of_week',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_hour',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_minute',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='cron_month_of_year',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
