# Generated by Django 2.2 on 2021-01-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20210123_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorjobversion',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobversion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
