# Generated by Django 2.2 on 2021-01-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20210129_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorjob',
            name='python_version',
        ),
        migrations.RemoveField(
            model_name='job',
            name='python_version',
        ),
    ]
