# Generated by Django 2.2 on 2021-02-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20210130_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorjob',
            name='server_url',
            field=models.TextField(default='http://127.0.0.1:8000/', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='server_url',
            field=models.TextField(default='http://127.0.0.1:8000/', max_length=300),
        ),
    ]
