# Generated by Django 2.2 on 2021-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20210220_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorjoblog',
            name='return_status_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblog',
            name='return_status_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
