# Generated by Django 2.2.19 on 2021-03-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20210304_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='password',
        ),
    ]
