# Generated by Django 2.2.19 on 2021-03-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_remove_job_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingscript',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingscriptversion',
            name='active',
            field=models.BooleanField(default=False),
        ),

    ]
