# Generated by Django 2.2.19 on 2021-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20210318_2159'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicatorjob',
            name='unique_indicatorjob_active',
        ),
        migrations.RemoveConstraint(
            model_name='indicatorjobversion',
            name='indicator_unique_job_version_active',
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_job_active',
        ),
        migrations.RemoveConstraint(
            model_name='jobversion',
            name='unique_job_version_active',
        ),
        migrations.RemoveConstraint(
            model_name='trainingscript',
            name='unique_script_active',
        ),
        migrations.RemoveConstraint(
            model_name='trainingscriptversion',
            name='unique_script_version_active',
        ),
        migrations.AddConstraint(
            model_name='indicatorjobversion',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('job', 'organization'), name='indicator_unique_job_version_active'),
        ),
        migrations.AddConstraint(
            model_name='jobversion',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('job', 'organization'), name='unique_job_version_active'),
        ),
        migrations.AddConstraint(
            model_name='trainingscript',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('organization',), name='unique_script_active'),
        ),
        migrations.AddConstraint(
            model_name='trainingscriptversion',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('script', 'organization'), name='unique_script_version_active'),
        ),
    ]
