# Generated by Django 2.2.19 on 2021-04-08 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20210325_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='train_start_date',
        ),
        migrations.AddField(
            model_name='modelversion',
            name='train_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indicatorjobversion',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False, validators=[django.core.validators.RegexValidator(message='must be valid versionString', regex='\\d\\.\\d\\.\\d')]),
        ),
        migrations.AlterField(
            model_name='jobversion',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False, validators=[django.core.validators.RegexValidator(message='must be valid versionString', regex='\\d\\.\\d\\.\\d')]),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='training_script_version',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.TrainingScriptVersion'),
        ),
        migrations.AlterField(
            model_name='trainingscriptversion',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False, validators=[django.core.validators.RegexValidator(message='must be valid versionString', regex='\\d\\.\\d\\.\\d')]),
        ),
    ]
