# Generated by Django 2.2.19 on 2021-04-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20210407_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='mitigated',
            field=models.BooleanField(default=False),
        ),
    ]
