# Generated by Django 2.2.19 on 2021-04-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20210409_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
