# Generated by Django 2.2.19 on 2021-04-09 23:31

from django.db import migrations

def remove_jobs(apps, schema_editor):
    jobs_version_mdl = apps.get_model('api', 'JobVersion')
    versions = jobs_version_mdl.objects.all().delete()
    jobs_mdl = apps.get_model('api', 'Job')
    jobs = jobs_mdl.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_job_user'),
    ]

    operations = [
        migrations.RunPython(remove_jobs)
    ]
