# Generated by Django 2.2.19 on 2021-04-13 00:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20210409_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseindicatorjob',
            name='arguments',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='arguments',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='UnmitigateIndicatorJobVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='unmitigate_job_scripts')),
                ('version', semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False, validators=[django.core.validators.RegexValidator(message='must be valid versionString', regex='\\d\\.\\d\\.\\d')])),
                ('active', models.BooleanField(default=False)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.UnmitigateIndicatorJob')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='MitigateIndicatorJobVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='mitigate_job_scripts')),
                ('version', semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False, validators=[django.core.validators.RegexValidator(message='must be valid versionString', regex='\\d\\.\\d\\.\\d')])),
                ('active', models.BooleanField(default=False)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.MitigateIndicatorJob')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unmitigateindicatorjobversion',
            constraint=models.UniqueConstraint(fields=('job', 'version', 'organization'), name='indicator_unique_unmitigate_job_version'),
        ),
        migrations.AddConstraint(
            model_name='unmitigateindicatorjobversion',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('job', 'organization'), name='indicator_unique_unmitigate_job_version_active'),
        ),
        migrations.AddConstraint(
            model_name='mitigateindicatorjobversion',
            constraint=models.UniqueConstraint(fields=('job', 'version', 'organization'), name='indicator_unique_mitigate_job_version'),
        ),
        migrations.AddConstraint(
            model_name='mitigateindicatorjobversion',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('job', 'organization'), name='indicator_unique_mitigate_job_version_active'),
        ),
    ]
