# Generated by Django 2.2.19 on 2021-04-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_auto_20210412_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorjoblog',
            name='task_id',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblog',
            name='task_id',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
    ]
