# Generated by Django 2.2.19 on 2021-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_auto_20210417_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobversion',
            name='task_create_script_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobversion',
            name='task_create_virtual_env',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mitigateindicatorjobversion',
            name='task_create_script_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mitigateindicatorjobversion',
            name='task_create_virtual_env',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='standardindicatorjobversion',
            name='task_create_script_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='standardindicatorjobversion',
            name='task_create_virtual_env',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainingscriptversion',
            name='task_create_script_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainingscriptversion',
            name='task_create_virtual_env',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unmitigateindicatorjobversion',
            name='task_create_script_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unmitigateindicatorjobversion',
            name='task_create_virtual_env',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
