# Generated by Django 2.2.19 on 2021-05-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20210418_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseindicatorjob',
            name='auto_mitigate',
            field=models.BooleanField(default=True),
        ),
    ]
