# Generated by Django 2.2.19 on 2021-05-13 02:23

from django.db import migrations

def remove_jobs(apps, schema_editor):
    mdl = apps.get_model('api', 'MitigateIndicatorJob')
    jobs = mdl.objects.all().delete()
    mdl = apps.get_model('api', 'UnMitigateIndicatorJob')
    jobs = mdl.objects.all().delete()
    mdl = apps.get_model('api', 'UnMitigateIndicatorJob')
    jobs = mdl.objects.all().delete()
    mdl = apps.get_model('api', 'StandardIndicatorJob')
    jobs = mdl.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_baseindicatorjob_auto_mitigate'),
    ]

    operations = [
        migrations.RunPython(remove_jobs)
    ]
