# Generated by Django 2.2.19 on 2021-05-13 02:30

from django.db import migrations

def remove_jobs(apps, schema_editor):
    mdl = apps.get_model('api', 'MitigateIndicatorJob')
    mdl.objects.all().delete()

    mdl = apps.get_model('api', 'BaseIndicatorJob')
    mdl.objects.all().delete()
 
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_auto_20210512_2223'),
    ]

    operations = [
        migrations.RunPython(remove_jobs)
    ]
