# Generated by Django 2.2.19 on 2021-05-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20210512_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseindicatorjob',
            name='auto_mitigate',
        ),
    ]
