# Generated by Django 2.2.19 on 2021-05-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_remove_baseindicatorjob_auto_mitigate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseindicatorjob',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='mitigateindicatorjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='standardindicatorjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unmitigateindicatorjob',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='baseindicatorjob',
            name='unique_indicatorjob',
        ),
        migrations.RemoveField(
            model_name='baseindicatorjob',
            name='name',
        ),
        migrations.RemoveField(
            model_name='baseindicatorjob',
            name='organization',
        ),
        migrations.AddField(
            model_name='mitigateindicatorjob',
            name='auto_mitigate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitigateindicatorjob',
            name='manual_mitigate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitigateindicatorjob',
            name='name',
            field=models.CharField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitigateindicatorjob',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardindicatorjob',
            name='name',
            field=models.CharField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardindicatorjob',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unmitigateindicatorjob',
            name='name',
            field=models.CharField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unmitigateindicatorjob',
            name='organization',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='mitigateindicatorjob',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_mitigateindicatorjob'),
        ),
        migrations.AddConstraint(
            model_name='mitigateindicatorjob',
            constraint=models.UniqueConstraint(condition=models.Q(auto_mitigate=True), fields=('indicator_type', 'organization'), name='mitigateindicatorjob_unique_auto_mitigate'),
        ),
        migrations.AddConstraint(
            model_name='mitigateindicatorjob',
            constraint=models.UniqueConstraint(condition=models.Q(manual_mitigate=True), fields=('indicator_type', 'organization'), name='mitigateindicatorjob_unique_manual_mitigate'),
        ),
        migrations.AddConstraint(
            model_name='standardindicatorjob',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_standard_indicatorjob'),
        ),
        migrations.AddConstraint(
            model_name='unmitigateindicatorjob',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_unmitigate_indicatorjob'),
        ),
    ]
