# Generated by Django 2.2.19 on 2021-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_auto_20210512_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='allowed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='mitigated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
