# Generated by Django 2.2.19 on 2021-10-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20210829_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='training_script',
        ),
        migrations.DeleteModel(
            name='FileUploadSource',
        ),
    ]
